config/routes.rb
Rails.application.routes.draw do

  root to: 'movies#index'

  resources :movies do 
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end
  get '/admin/next_users_page', to: 'admin/users#next_page'
  get '/admin/prev_users_page', to: 'admin/users#prev_page' 

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  scope :title_includes, ->(title_text) { where("title LIKE ?", "%#{title_text}%") }
  scope :director_includes, ->(dir_text) { where("director LIKE ?", "%#{dir_text}%") }
  scope :less_than_90_mins_long, -> { where("runtime_in_minutes < 90") }
  scope :from_90_to_120_mins_long, -> { where("runtime_in_minutes >= 90 AND runtime_in_minutes <= 120") }
  scope :more_than_120_mins_long, -> { where("runtime_in_minutes > 120") }

  has_many :reviews

  mount_uploader :poster, PosterUploader

  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }
  validates :description, presence: true
  # validates :poster_image_url, presence: true
  validates :release_date, presence: true
  # validate :release_date_is_in_the_future

  def review_average
    if !reviews.empty?
      return reviews.sum(:rating_out_of_ten)/reviews.size
    else
      return '-'
    end
  end

protected
  
  # def release_date_is_in_the_future
  #   if release_date.present?
  #     errors.add(:release_date, "should probably be in the future") if release_date < Date.today
  #   end
  # end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: { only_integer: true }
  validates :rating_out_of_ten, numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten, numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_admin_access

  def index
    max_per_page = 10
    num_users = User.count
    @max_pages = num_users / max_per_page
    @max_pages += 1 if (num_users % max_per_page) > 0
    session[:admin_users_page] ||= 1
    session[:admin_users_page] = 1 if session[:admin_users_page] < 1
    session[:admin_users_page] = @max_pages if session[:admin_users_page] > @max_pages
    @users_page = User.page(session[:admin_users_page]).per(max_per_page)
  end

  def next_page
    session[:admin_users_page] += 1
    redirect_to admin_users_path
  end

  def prev_page
    session[:admin_users_page] -= 1
    redirect_to admin_users_path
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.deletion_email(@user)
    destroyed_user_full_name = @user.full_name
    @user.destroy
    redirect_to admin_users_path, notice: "User: #{destroyed_user_full_name} destroyed."
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(admin_user_params)
    if @user.save
      redirect_to admin_users_path, notice: "User: #{@user.full_name} created."
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(admin_user_params)
      redirect_to admin_users_path, notice: "#User: {@user.full_name} updated."
    else
      render :edit
    end
  end

protected
  
  def restrict_admin_access
    @current_user = User.find(session[:user_id]) if session[:user_id]
    if (@current_user == nil) || (@current_user.admin != true)
      redirect_to movies_path
    end
  end

  def admin_user_params
    params.require(:user).permit(:email, :firstname, :lastname, :admin, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

def restrict_access
  if !current_user
    flash[:alert] = "Please log in."
    redirect_to new_session_path
  end
end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
    handle_index_search
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

protected 

  def movie_params
    params.require(:movie).permit(
      :title,
      :release_date,
      :director,
      :runtime_in_minutes,
      :poster_image_url,
      :poster,
      :description
    )
  end

  def handle_index_search
    @movies = @movies.title_includes(params[:t]) if params[:t].present?
    @movies = @movies.director_includes(params[:d]) if params[:d].present?
    if params[:length].present?
      case params[:length]
      when 'less90'
        @movies = @movies.less_than_90_mins_long
      when '90to120'
        @movies = @movies.from_90_to_120_mins_long
      when '120more'
        @movies = @movies.more_than_120_mins_long
      end
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access

  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to @movie, notice: "Review created successfully."
    else
      render :new
    end
  end

protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Hola, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Bye."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

protected
  
  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "admin", "Admin" %>
    <%= f.check_box "admin" %>
  </div>
  <br>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Admin Edit User</h1>
<%= form_for [:admin, @user] do |f| %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "admin", "Admin" %>
    <%= f.check_box "admin" %>
  </div>
  <br>
  <div><%= f.submit "Submit" %></div>
<% end %>
<br>
<br>
<%= link_to "Back to User Index", admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Admin User Control</h1>
<hr>
<%= link_to "Create New User", new_admin_user_path %>
<hr>
<div>
  <%= link_to "<< Previous Page", admin_prev_users_page_path %> | Page <%= session[:admin_users_page] %> of <%= @max_pages %> | <%= link_to "Next Page >>", admin_next_users_page_path %>
</div>
<hr>
<% @users_page.each do |user| %>
  <h2>User ID: <%= user.id %> -- <%= user.email %></h2>
  <p>Full Name: <%= user.full_name %></p>
  <p>(<%= link_to "edit", edit_admin_user_path(user) %>)(<%= link_to "delete", admin_user_path(user), data: {confirm: 'Are you sure?'}, method: :delete %>)</p>
  <p><%= link_to "See Full Entry", admin_user_path(user) %></p>
  <hr>
<% end %>

app/views/admin/users/new.html.erb
<h1>Admin New User</h1>
<%= form_for [:admin, @user] do |f| %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
   <div>
    <%= f.label "admin", "Admin" %>
    <%= f.check_box "admin" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>
<br>
<br>
<%= link_to "Back to User Index", admin_users_path %>

app/views/admin/users/show.html.erb
<h1>User Details</h1>
<h2>User ID: <%= @user.id %> -- <%= @user.email %></h2>
<p>Full Name: <%= @user.full_name %></p>
<h3>Reviews</h3>
<% @user.reviews.each do |review| %>
  <h4><%= review.movie.title %></h4>
  <ul>
    <li>Rating: <%= review.rating_out_of_ten %>/10</li>
    <li>Character Count: <%= review.text.length %></li>
    <li>Creation Date: <%= formatted_date(review.created_at) %></li>
  </ul>
<% end %>
<%= link_to "Back to Admin User Index", admin_users_path %>
<hr>

app/views/layouts/_footer.html.erb
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; elsieC 2014</p>
        </div>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>RottenMangoes</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>

                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <% if current_user %>
                    <li>
                         <a><%= link_to "Log out", session_path("current"), method: :delete %></a>
                    </li>
                    <li>
                        <a><%= link_to "Submit a Movie", new_movie_path %></a>
                    </li>
                      <% else %>
                     <li>
                      <a>  <%= link_to "Log In", new_session_path %></a> 
                    </li>  
                    <li>
                        <a></a>
                    </li>
                     <li>
                        <a><%= link_to "Sign Up", new_user_path %></a>
                    </li>
                      <% end %>
                   
                    

                </ul>
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
               <h1 class="page-header">Rotten Mangoes
                    <% if current_user %>
                  <small>Hi <%= current_user.full_name %></small>
                  <% end %>
                   <% flash.each do |key, value| %>
                  <small><%= content_tag(:div, value) %></small>
                  <% end %>
              </h1>
          </div>
        </div>            
    </nav>     
<div id= "spaced"></div>
<div class="container-fluid">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted: 
        <ul>
          <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.number_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label "poster_image_url" %><br>
    <%= f.text_field "poster_image_url" %>
  </div>
  <div>
    <%= f.label "poster" %><br>
    <%= f.file_field "poster" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.submit "Submit Changes" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<!-- <h2><%= link_to movie.title, movie_path(movie) %></h2> -->
<!-- <div class="col-md-2">
  <%= link_to image_tag(movie.poster_url.to_s, class: "thumbnail"), movie_path(movie) %>
</div>
<div class="col-md-8">
  <small>(<%= link_to "edit this movie", edit_movie_path(movie) %>)</small>
  <p>Rating: <%= movie.review_average %>/10</p>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Directed by:  <%= movie.director %> | Runtime: <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p>
</div> -->



<div class="container">
    <div class="row">
        <div class="col-md-2">
        <a class: "thumbnail">  <%= link_to image_tag(movie.poster_url.to_s), movie_path(movie) %></a>
        </div>
        <div class="col-md-7">
          <small>(<%= link_to "edit this movie", edit_movie_path(movie) %>)</small>
          <p>Rating: <%= movie.review_average %>/10</p>
          <h3><%= formatted_date(movie.release_date) %></h3>
          <h4>Directed by:  <%= movie.director %> | Runtime: <%= movie.runtime_in_minutes %> minutes</h4>
          <p><%= movie.description %></p>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row"></div>
</div>

app/views/movies/_search.html.erb
  <div>
      <%= form_tag(movies_path, method: 'get', class: "form-inline") do %>
        <div class="form-group">
          <%= label_tag(:t, "Enter Movie Title or Director") %>
          <%= text_field_tag(:t) %>
        </div>
        <!-- <%= label_tag(:d, "Search Movie Director:") %>
        <%= text_field_tag(:d) %> -->
        <div class="form-group">
        <%= label_tag(:length, "Movie Length:") %>
        <%= select_tag(:length, "<option value='less90'>Under 90 Minutes</option><option value='90to120'>From 90 to 120 Minutes</option><option value='120more'>More Than 120 Minutes</option>".html_safe, include_blank: true) %>
      </div>
        <%= submit_tag("Search") %>
      <% end %>
</div>
<!-- <% if params[:t].present? %>
  <p>Movies with '<%= params[:t] %>' in the title</p>
<% end %>
<% if params[:d].present? %>
  <p>Movies with '<%= params[:d] %>' in the director name</p>
<% end %>
<% if params[:length].present? %>
  <% case params[:length] %>
  <% when 'less90' %>
    <p>Movies shorter than 90 minutes</p>
  <% when '90to120' %>
    <p>Movies from 90 minutes to 120 minutes</p>
  <% when '120more' %>
    <p>Movies longer than 120 minutes</p>
  <% end %>
<% end %> -->

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>
<h2>Edit this movie...</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
</div>
<div class="row">
  <%= render 'search'%>

</div>
<div class="row">
</div>
<div class="row">
    <li class = "movie_list_item"><%= render @movies %></li>
</div>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>
<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %>
<br>
<%= link_to image_tag(@movie.poster_image_url), movie_path(@movie) %>
<%= image_tag @movie.poster_url.to_s %>
<h2><%= link_to @movie.title, movie_path(@movie) %></h2>
<small>(<%= link_to "edit this movie", edit_movie_path(@movie) %>)</small>
<p>Rating: <%= @movie.review_average %>/10</p>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Directed by:  <%= @movie.director %> | Runtime: <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews for <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/reviews/new.html.erb
 <%= link_to "Back to movie", movie_path(@movie) %><br/>

    <h2>Write a review of <em><%= @movie.title %></em>.</h2>

    <%= form_for([@movie, @review]) do |f| %>
      <% if @review.errors.any? %>
        <div>
          <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
          <ul>
            <% @review.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= f.label "text" %><br>
        <%= f.text_area "text" %>
      </div>
      <div>
        <%= f.label "rating_out_of_ten" %><br>
        <%= f.number_field "rating_out_of_ten" %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<!-- Errors -->
<% if @user.errors.any? %>
  <div>
    <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<!-- Form -->
<%= form_for @user do |f| %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>